### ISSUE TITLE
Modify Upload Page

### ISSUE THREAD

**Issue by dpham123** [CS157A-Team18/CS157A-Team18#42]
- The ingredients list only displays the first 5 ingredients. The rest of the ingredients are out of view. The page should expand as the user adds ingredients.
![image.png](https://images.zenhubusercontent.com/5d33c3f0fb420457c843a08d/cbdcbd10-3e51-47bd-b268-05d706b5c597)
- The delete button should remove an ingredient immediately without confirmation for speed. Accidentally deleting an ingredient isn't a big issue.
![image.png](https://images.zenhubusercontent.com/5d33c3f0fb420457c843a08d/6d659bca-e0c8-40a4-8d0d-55f18d0068a6)
- `Description` should be changed to `Instructions`. The process of adding instructions should be similar to adding the ingredients for the recipe.
![image.png](https://images.zenhubusercontent.com/5d33c3f0fb420457c843a08d/d6b659c6-12dd-4dbf-9c6e-26120a2dc9d5)

**Comment by KimlengHor** [comment]
For the material ui library, the onRowDelete must return a new Promise, so I cannot remove the confirmation dialog. I hope in the future, they will have an option where we can disable the dialog.
